name: planet_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  calendar_timeline: ^1.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\trees_welcome_screen.png
    - assets\Vector 1.png
    - assets\profile.jpg

          
